# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://atlas.hashicorp.com/search.
    config.vm.box = "ubuntu/trusty64"

    # Name the Vagrant instance
    config.vm.define "TorchVagrantBox"

    #Configure synced folders
    config.vm.synced_folder "../", "/vagrant"

    # Forwarding our ports
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.network "forwarded_port", guest: 3000, host: 3000
    config.vm.network "forwarded_port", guest: 4000, host: 4000
    config.vm.network "forwarded_port", guest: 8000, host: 8000
    config.vm.network "forwarded_port", guest: 8100, host: 8100
    config.vm.network "forwarded_port", guest: 9000, host: 9000
    config.vm.network "forwarded_port", guest: 27017, host: 27017
    config.vm.network "forwarded_port", guest: 35729, host: 35729

    # Forwarding our display for graphical programs
    # Must install xauth on host machine (sudo apt-get install xauth)
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true

    # Customize our virtualbox
    config.vm.provider :virtualbox do |vb|

        # Add support for audio
        # vb.customize [
        #   "modifyvm", :id,
        #    "--audio", "alsa",
        #    "--audiocontroller", "hda"
        # ]

        #Set Virtualbox memory
        vb.customize [
            "modifyvm", :id,
            "--name", "TorchVagrantBox",
            "--memory", "1024"
        ]

        #Speed up ruby gems install
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
    end

    #Run my bootstrap script
    config.vm.provision :shell, path: "bootstrap.sh", privileged: true, keep_color: true
end
